version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: contact-management-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: contact-management-web
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge